ALTER TABLE signals ADD COLUMN IF NOT EXISTS strength VARCHAR(16) DEFAULT 'weak';
ALTER TABLE signals ADD COLUMN IF NOT EXISTS risk_level VARCHAR(16) DEFAULT 'medium';
ALTER TABLE signals ADD COLUMN IF NOT EXISTS reason_summary TEXT DEFAULT '';
ALTER TABLE signals ADD COLUMN IF NOT EXISTS indicators_used JSONB DEFAULT '[]'::jsonb;
ALTER TABLE signals ADD COLUMN IF NOT EXISTS invalidation_price DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE signals ADD COLUMN IF NOT EXISTS data_source VARCHAR(16) DEFAULT 'synthetic';
